// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/client-dashboard/Atelier.tsx": () => import("../components/mockups/client-dashboard/Atelier.tsx"),
  "./components/mockups/client-dashboard/Aurora.tsx": () => import("../components/mockups/client-dashboard/Aurora.tsx"),
  "./components/mockups/client-dashboard/Brief.tsx": () => import("../components/mockups/client-dashboard/Brief.tsx"),
  "./components/mockups/client-dashboard/Catalyst.tsx": () => import("../components/mockups/client-dashboard/Catalyst.tsx"),
  "./components/mockups/client-dashboard/Clarity.tsx": () => import("../components/mockups/client-dashboard/Clarity.tsx"),
  "./components/mockups/client-dashboard/Command.tsx": () => import("../components/mockups/client-dashboard/Command.tsx"),
  "./components/mockups/client-dashboard/Forge.tsx": () => import("../components/mockups/client-dashboard/Forge.tsx"),
  "./components/mockups/client-dashboard/Sprint.tsx": () => import("../components/mockups/client-dashboard/Sprint.tsx"),
  "./components/mockups/client-dashboard/StudioAI.tsx": () => import("../components/mockups/client-dashboard/StudioAI.tsx")
};
