// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/client-dashboard/Aurora.tsx": () => import("../components/mockups/client-dashboard/Aurora.tsx"),
  "./components/mockups/client-dashboard/Brief.tsx": () => import("../components/mockups/client-dashboard/Brief.tsx"),
  "./components/mockups/client-dashboard/Clarity.tsx": () => import("../components/mockups/client-dashboard/Clarity.tsx")
};
